---

APPLICATION_UID:     "{{ lookup('env', 'APPLICATION_UID') }}"
APPLICATION_GID:     "{{ lookup('env', 'APPLICATION_GID') }}"

BURP_VERSION:        "2.0.46"

# Burp Cronjobs
ENABLE_CRON_DEDUP:   "{{ lookup('env', 'ENABLE_CRON_DEDUP') | default(True) }}"
ENABLE_CRON_SUMMARY: "{{ lookup('env', 'ENABLE_CRON_SUMMARY') | default(False) }}"
BURP_EMAIL:          "{{ lookup('env', 'BURP_EMAIL') }}"
